
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA\n    palindromo : CADENA\n               | CADENA palindromo\n    '
    
_lr_action_items = {'CADENA':([0,2,],[2,2,]),'$end':([1,2,3,],[0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'palindromo':([0,2,],[1,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> palindromo","S'",1,None,None,None),
  ('palindromo -> CADENA','palindromo',1,'p_palindromo','g_palindromo.py',21),
  ('palindromo -> CADENA palindromo','palindromo',2,'p_palindromo','g_palindromo.py',22),
]
